global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "spring-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8082"]

  - job_name: "kafka-jmx"
    metrics_path: /metrics
    static_configs:
      - targets: ["kafka:7071"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
